services:
    jenkins:
        container_name: jenkins
        user: root
        image: jenkins/jenkins:lts-alpine-jdk17
        ports:
            - "8081:8080"
            - "50000:50000"
        volumes:
            - ./jenkins_home:/var/jenkins_home
